In [1]:
# import libraries
import pandas as pd
import numpy as np

In [2]:
# dummy dataset
data ={'Temperature':['Hot','cold','Very Hot','Warm','Hot','Warm','Warm','Hot','Hot','cold'],
       'Color':['Red','Yellow','Blue','Blue','Red','Yellow','Red','Yellow','Yellow','Yellow'],
       'Target':[1,1,1,0,1,0,1,0,1,1]}

In [3]:
# convert into dataframe
df = pd.DataFrame(data, columns=['Temperature','Color','Target'])
df

  Temperature   Color  Target
0         Hot     Red       1
1        cold  Yellow       1
2    Very Hot    Blue       1
3        Warm    Blue       0
4         Hot     Red       1
5        Warm  Yellow       0
6        Warm     Red       1
7         Hot  Yellow       0
8         Hot  Yellow       1
9        cold  Yellow       1

In [25]:
#df = pd.get_dummies(df, prefix=['Temp'], columns=['Temperature'])

In [5]:
from sklearn.preprocessing import OneHotEncoder

In [6]:
# apply onehotencoder to convert categorical feature to numerical feature
ohc = OneHotEncoder()
ohe = ohc.fit_transform(df.Temperature.values.reshape(-1,1)).toarray()
dfOneHot = pd.DataFrame(ohe,columns = ["Temp_"+str(ohc.categories_[0][i]) for i in range(len(ohc.categories_[0]))])
dfh = pd.concat([df, dfOneHot],axis=1)
dfh

  Temperature   Color  Target  Temp_Hot  Temp_Very Hot  Temp_Warm  Temp_cold
0         Hot     Red       1       1.0            0.0        0.0        0.0
1        cold  Yellow       1       0.0            0.0        0.0        1.0
2    Very Hot    Blue       1       0.0            1.0        0.0        0.0
3        Warm    Blue       0       0.0            0.0        1.0        0.0
4         Hot     Red       1       1.0            0.0        0.0        0.0
5        Warm  Yellow       0       0.0            0.0        1.0        0.0
6        Warm     Red       1       0.0            0.0        1.0        0.0
7         Hot  Yellow       0       1.0            0.0        0.0        0.0
8         Hot  Yellow       1       1.0            0.0        0.0        0.0
9        cold  Yellow       1       0.0            0.0        0.0        1.0

In [8]:
# apply label encoder to convert categorical feature to numerical feature
from sklearn.preprocessing import LabelEncoder
df['Temp_label_encoded'] = LabelEncoder().fit_transform(df.Temperature)
df

  Temperature   Color  Target  Temp_label_encoded
0         Hot     Red       1                   0
1        cold  Yellow       1                   3
2    Very Hot    Blue       1                   1
3        Warm    Blue       0                   2
4         Hot     Red       1                   0
5        Warm  Yellow       0                   2
6        Warm     Red       1                   2
7         Hot  Yellow       0                   0
8         Hot  Yellow       1                   0
9        cold  Yellow       1                   3